### ISSUE TITLE
按照使用方式使用，并没有提示可以快速生成 useState

### ISSUE THREAD

**Issue by yxb94616** [a145789/vscode-quick-useState#1]
使用的 vscode 环境:
Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

使用截图:
![image](https://user-images.githubusercontent.com/20277731/201280574-30611252-78b8-484e-be25-3d7620065587.png)

**Comment by a145789** [comment]
#2
